version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: salas_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salas_estudio
      MYSQL_USER: salas_user
      MYSQL_PASSWORD: salas_pass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql:ro
      - ./db/02_datos_iniciales.sql:/docker-entrypoint-initdb.d/02_datos_iniciales.sql:ro

  api:
    build: ./backend
    container_name: salas_api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: salas_estudio
      DB_USER: salas_user
      DB_PASSWORD: salas_pass
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    command: >
      uvicorn app.servidor:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data: {}
